# Generated by Django 3.1.4 on 2021-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=1000)),
                ('type', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('resources', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
