# Generated by Django 3.1.4 on 2021-05-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdiary', '0005_auto_20210424_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='comment',
            field=models.TextField(max_length=5000),
        ),
    ]
