# Generated by Django 3.1.4 on 2021-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdiary', '0007_auto_20210510_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done_indicator',
            field=models.IntegerField(default=-1),
        ),
    ]
